---
# This play uses the motd role to update the motd page
# for the target systems
#
- name: "Apply the post-provisioning configuration"
  hosts: all
  become: true
  vars_files:
    - /etc/ansible/vault/ipa_vault.yml
    - /etc/ansible/vault/satellite_vault.yml

  tasks:
    - name: "Info:"
      ansible.builtin.debug:
        msg: Post Provisioning Setup

  roles:
    - cockpit
    - time
    - sysmessage
    - cockpit_cert
